;
; Maple Story 2 Config.ini
;

[ModelData]
ModelDir = Data\Resource\Exported

[AssetWeb]
Path = Data\Resource

[Data]
Path = Data\Resource
BlockFile = $(Map)
EnableShadows = true
EnableHUD = true
FOV = 40.0

[Scheduler]
ShardID = 156

[ScriptEngine.Lua]
SystemScriptPath# = $(EMERGENT_PATH)\SDK\Win32\Lua
UserScriptPath# = .
LoadBuiltin# = egfLua!luaopen_BehaviorAPI
LoadBuiltin# = ecr!luaopen_ecr
LoadBuiltin# = egmAnimationLua!luaopen_egmAnimation

[Test]
MaxGameTicks=0

[NetService]
NetLibType=NetLib

[Enum]
Path = $(EMERGENT_PATH)\Media\Enums

[Log]
ModuleEnum = egfLogIDs

; We use log module id's in case we don't have an Enum Manager initialized
[Log.Filters]
0 = UptoErr1            ;ALL
19 = Lvl3               ;GamebryoGeneral0
20 = Lvl3               ;GamebryoGeneral2
21 = Lvl3               ;GamebryoMemory0
22 = Lvl3               ;GamebryoMemory1
23 = Lvl3               ;GamebryoMemory2
24 = Lvl3               ;GamebryoMemoryTimeStamp
25 = Lvl3               ;GamebryoReserved

[PhysX.SDK]
VRDHost=

[PhysX.Framework]
DisableDebugRendererForTerrain = true

; Share CPU with Toolbench when iterating on content
[ServiceManager]
Sleep=1
DeactivatedSleep=100

[VisualTracker]
PerfMaxValue=600.0
TimingMaxValue=20.0

[GFx]
Path = ./Data/Resource/
LocalizationConfig = GFxAssets/fontconfig.txt
Language = Korean
EdgeAA = true

[Renderer.Win32]
ScreenWidth=1024
ScreenHeight=768
MinScreenWidth=1024
MinScreenHeight=768
VertexProcessing=1
DX9RenderTargetMode=3
DX9DepthSurfaceMode=75
DX9FrameBufferMode=0
D3D10OutputIdx=0
D3D10MultisampleCount=1
D3D10MultisampleQuality=0
D3D10DSFormat=45
D3D10RTFormat=28
D3D11OutputIdx=0
D3D11MultisampleCount=1
D3D11MultisampleQuality=0
D3D11DSFormat=45
D3D11RTFormat=28
D3D11FeatureLevel9_1=1
D3D11FeatureLevel9_2=1
D3D11FeatureLevel9_3=1
D3D11FeatureLevel10_0=1
D3D11FeatureLevel10_1=1
D3D11FeatureLevel11_0=1
RendererID=2
Fullscreen=0
NVPerfHUD=0
RefRast=0
Use16Bit=0
PureDevice=1
VSync=0
MultiThread=1
RendererDialog=0
